### ISSUE TITLE
Encountered a build error when run "cargo run" cmd for the testnet node setup 

### ISSUE THREAD

**Issue by ivy191118** [ParaState/frontier#45] opened 2021-07-02 03:03 UTC
**Question**

Hi Team, we encounter an error when setup a testnet node, please help to take a look at.

**Server enrironment:**
OS: Ubuntu18.04
Environment setup: use Manual Installation steps
cmake: upgrade to 3.11.3

**Run cmd:**
cargo run --release --bin frontier-template-node --
--execution=Native
--base-path ./data
--chain ./specs/2021-04-22-spec-raw.json
--port 30333
--rpc-port 9933
--ws-port 9944
--validator
--telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'
--name 'RockX'
--bootnodes /ip4/13.67.57.72/tcp/30333/p2p/12D3KooWNwpkJk3f4fUEc9cjSzLC5xE3opf25pjt7izfNGc1v5Tu

**ERROR MESSAGE:**

utils/ssvm-core/lib/host/wasi/CMakeFiles/ssvmHostModuleWasi.dir/build.make:75: recipe for target 'utils/ssvm-core/lib/host/wasi/CMakeFiles/ssvmHostModuleWasi.dir/wasifunc.cpp.o' failed
CMakeFiles/Makefile2:480: recipe for target 'utils/ssvm-core/lib/host/wasi/CMakeFiles/ssvmHostModuleWasi.dir/all' failed
Makefile:129: recipe for target 'all' failed

--- stderr
CMake Warning:
Manually-specified variables were not used by the project:

  CMAKE_ASM_COMPILER
  CMAKE_ASM_FLAGS
/opt/rockx/frontier/target/release/build/rust-ssvm-7a2db71a1154b5bb/out/build/_deps/ssvm-src/lib/host/wasi/wasifunc.cpp: In member function ‘SSVM::Expect SSVM::Host::WasiPathOpen::body(SSVM::Runtime::Instance::MemoryInstance*, int32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint64_t, uint64_t, uint32_t, uint32_t)’:
/opt/rockx/frontier/target/release/build/rust-ssvm-7a2db71a1154b5bb/out/build/_deps/ssvm-src/lib/host/wasi/wasifunc.cpp:1689:12: error: ‘class std::experimental::filesystem::v1::__cxx11::path’ has no member named ‘lexically_normal’
.lexically_normal()
^~~~~~~~~~~~~~~~
make[2]: *** [utils/ssvm-core/lib/host/wasi/CMakeFiles/ssvmHostModuleWasi.dir/wasifunc.cpp.o] Error 1
make[1]: *** [utils/ssvm-core/lib/host/wasi/CMakeFiles/ssvmHostModuleWasi.dir/all] Error 2
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit status: 2

build script failed, must exit now', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by hydai** [comment] 2021-07-02 07:08
cc @dm4 
Please reproduce this issue. And check our deps if there is any change that we didn't apply to this project.

**Comment by dm4** [comment] 2021-07-05 06:19
Hi, @ivy191118 

This error message is due to compiler version too old. The feature is supported after gcc 8.1 and clang 7. You can try the following command:

```
apt install gcc-8 g++-8
export CC=gcc-8
export CXX=g++-8
cargo build --release
```

I'll update our guideline later and thanks for your feedback!

**Comment by ivy-stone** [comment] 2021-07-06 03:35
Hi team,
the build problem is fixed after upgrade to gcc-8,g++-8.
Thank you very much.

**Comment by ivy191118** [comment] 2021-07-06 03:37
Hi team,
The problem is fixed after upgrade to gcc-8 and g++-8.
Thank you very much!

**Comment by hydai** [comment] 2021-07-12 02:56
Looks like this issue is resolved. I'm going to close it. Thanks!

**Closed as completed by hydai** 2021-07-12 02:56 UTC
Labels: question
